# Generated by Django 5.0.4 on 2024-09-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carplates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parked_at', models.DateTimeField(auto_now_add=True)),
                ('unparked_at', models.DateTimeField()),
                ('parked_time', models.TimeField()),
                ('value', models.FloatField(default=0)),
                ('carplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carplates.carplate')),
            ],
        ),
    ]
