# Generated by Django 5.0.4 on 2024-09-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10)),
                ('parking_count', models.IntegerField(default=0)),
                ('parked_now', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
    ]
